name: test-workflow
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Semantic version tag (format should be v[number].[number].[number])'
                required: true
                type: string
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+
env:
    USERNAME: m-rakic-vegait
    IMAGE_NAME: test-devops-app
    REGISTRY_URL: ghcr.io
jobs:
    build-and-push-image:
        if: (github.event_name == 'workflow_dispatch' && ${{ inputs.tag }} =~ v[0-9]+.[0-9]+.[0-9]+) || github.event_name == 'push'
        runs-on: ubuntu-latest
        environment: test-devops-env
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.USERNAME }}
                  password: ${{ secrets.GH_TOKEN }}
                  registry: ${{ env.REGISTRY_URL }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Buld image and push - workflow_dispatch
              if: github.event_name == 'workflow_dispatch'
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{ env.REGISTRY_URL }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
            - name: Buld image and push - push
              if: github.event_name == 'push'
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{ env.REGISTRY_URL }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
