name: test-workflow
on:
    workflow_dispatch:
        inputs:
            testdevopssecret:
                type: string
                required: true
                description: 'test access secrets'
                default: ${{ github.env.TEST_DEVOPS_SECRET }}
# env:
#     USERNAME: m-rakic-vegait
#     IMAGE_NAME: test-devops-app
#     REGISTRY_URL: ghcr.io
#     GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout the repo
            #   uses: actions/checkout@v4
            - name: Build image
              run: |
                  echo GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  echo MY_SECRET: ${{ secrets.MY_SECRET }}
                  echo TEST_DEVOPS_SECRET: ${{ inputs.testdevopssecret }}
                  echo GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Log in to Registry
            #   run: |
            #     echo ${GH_TOKEN}
            #     docker login ${REGISTRY_URL} --username ${USERNAME} --password-stdin
            # - name: Push image
            #   run: docker push ${REGISTRY_URL}/${USERNAME}/${IMAGE_NAME}:latest
