name: test-workflow
on:
    workflow_dispatch:
env:
    USERNAME: m-rakic-vegait
    IMAGE_NAME: test-devops-app
    REGISTRY_URL: ghcr.io
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        environment: test-devops-env
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4
            - name: Build image
              run: |
                  echo GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  echo MY_SECRET: ${{ secrets.MY_SECRET }}
                  echo TEST_DEVOPS_SECRET: ${{ secrets.TEST_DEVOPS_SECRET }}
                  echo GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  echo REGISTRY_URL: ${REGISTRY_URL}
                  echo USERNAME: ${USERNAME}
            # - name: Log in to Registry
            #   run: |
            #     echo ${GH_TOKEN}
            #     docker login ${REGISTRY_URL} --username ${USERNAME} --password-stdin
            # - name: Push image
            #   run: docker push ${REGISTRY_URL}/${USERNAME}/${IMAGE_NAME}:latest
