name: test-workflow
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Semantic version tag (format should be v[number].[number].[number])'
                required: true
                default: 'latest'
                type: string
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+
env:
    USERNAME: m-rakic-vegait
    IMAGE_NAME: test-devops-app
    REGISTRY_URL: ghcr.io
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        environment: test-devops-env
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.USERNAME }}
                  password: ${{ secrets.GH_TOKEN }}
                  registry: ${{ env.REGISTRY_URL }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set tag
              id: tag-selector
              run: |
                  if [ ${{ github.ref_type == "tag" }} ]; then
                    echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
                  else
                    echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
                  fi

            - name: Buld image and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{ env.REGISTRY_URL }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag-selector.outputs.tag }}
